travis:
  secure:
    BINSTAR_TOKEN: OtB9BD7wGS0L4bl8e990A6pTZpmpnERNvnuZrzT8gYUKU+hEIYX98BYUTxXmBtObMOFYgHsK22hrGDpFjb9J6ZWHAqlumwQrGxRnNEclksNuxAYMSwmmSzPthtBUNKq2/SC8qnKxK3ofMKbpcNwunUWWn1JzY14/pg3vQIcNirP7/0nxfctpYkOQQ9Jz0AXmqVICt/VnISSU0i59z7sh2tdT0HqzN9CeSsrMPyuUW1fCnh0UrX38k7D1bgoYb2dYwtFha44gb3uqt5YxHBsLShrbVJIPiQXGugGaQnSbQSaV4IJsNE/74a0aguyYZadIofbB3UPiT7INhNghCtzAmPaCQwp9gLEWgYzUyQnbQ6174b0eZw3I35rwGf64EbHNvUowkTXLXmWUatV+0CqWvXUmULq7Grfy3rMUu01C4LT8SDyuMB3M/djroysdbDGcvVFLWWgzQd7AEvxc/Dq788RbXljaKnT91GpxbxJ8cTsV5KLZ2awj67fqnTyqQSheAoopBx2vM72YeVK13zjF1HBdVXMBguinjYgIpvHQmkyKaxulc6ljQbRKmLy8lFQQxYao7iQQUW3PssQyKMWw/3cXt2t9i5NBXhpN53RZxdxq6OaaHkdQ5syuK2mNy0iSAYyh6i+9dgi//RNqzhqRYQZmJr7BoMVieSAC/Kut8eA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
